version: '3.1'

services:

  db16:
    image: postgres:13.0
    restart: always
    container_name: db16
    networks:
      - pg
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
  
  odoo:
    image: pandoo/odoo:16.0-amd64
    restart: always
    container_name: odoo
    ports:
      - 8069:8069
    networks:
      - pg
    links:
      - db16:db
    environment:
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./config:/etc/odoo
      - ~/Code/odoo-ee/15.0/:/mnt/enterprise-addons
      # Add volumes according to your odoo.conf
      # - ~/Code/addons/15.0/extra:/mnt/extra-addons
    tty: true

networks:
  pg:
