version: '3.1'

services:

  db15:
    image: postgres:13.0
    restart: always
    container_name: db15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=admin

  odoo:
    image: pandoo/odoo:15.0-arm64
    restart: always
    container_name: odoo
    depends_on:
      - db15
    ports:
      - 8069:8069
    environment:
      - HOST=db15
      - USER=odoo
      - PASSWORD=admin
    volumes:
      - ./config:/etc/odoo/
      - ~/Code/odoo-ee/15.0/:/mnt/enterprise/
      # Add volumes according to your odoo.conf
      # - ~/Code/addons/15.0/extra:/mnt/extra-addons
    tty: true

