version: '3.1'

services:
  
  odoo:
    image: odoo:15.0
    restart: always
    container_name: odoo
    ports:
      - 8069:8069
    networks:
      - pg
    links:
      - db15:db
    environment:
      USER: odoo
      PASSWORD: admin
    volumes:
      - ./config:/etc/odoo
      - ~/Code/odoo-ee/15.0:/mnt/enterprise/
      # crear las rutas locales
      # - ~/Code/addons/8.0:/mnt/extra-addons
      # - ~/Code/addons/8.0/testing:/mnt/extra-addons
      
  db15:
    image: postgres:10.0
    restart: always
    container_name: db15
    networks:
      - pg
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: admin

networks:
  pg:
